name: gymnasium-emulator
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pillow
  - pytorch             # Will be installed from the pytorch channel
  - pytorch-cuda=11.8   # Provides the matching CUDA runtime
  - python-dotenv
  - pygame
  - pip
  - pip:
      - vizdoom
      - ale-py
      - gymnasium[atari]
      - datasets
